
package Vistas;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Deb APBT
 */
public class MenuEscritorio extends javax.swing.JFrame {

    /**
     * Creates new form MenuEscritorio
     */
    public MenuEscritorio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon imgEsc = new ImageIcon(getClass().getResource("/Recursos/Escritorio.jpg"));
        Image miImagen = imgEsc.getImage();
        escritorio = new javax.swing.JDesktopPane(){

            public void paintComponent(Graphics g){
                g.drawImage(miImagen,0,0,getWidth(),getHeight(),this);
            }

        };
        jMenuBar2 = new javax.swing.JMenuBar();
        jVenta = new javax.swing.JMenu();
        jPasaje = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        JMenuBuscarHorarioPorSalida = new javax.swing.JMenuItem();
        jBuscarHorarios = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 668, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        jVenta.setText("Ventas");

        jPasaje.setText("Comprar Pasaje");
        jPasaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasajeActionPerformed(evt);
            }
        });
        jVenta.add(jPasaje);

        jMenuBar2.add(jVenta);

        jMenu5.setText("Gestion");
        jMenu5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu5ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Pasajeros");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem1);

        jMenuItem2.setText("Agregar Horarios");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem2);

        JMenuBuscarHorarioPorSalida.setText("Buscar Horario por Salida");
        JMenuBuscarHorarioPorSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuBuscarHorarioPorSalidaActionPerformed(evt);
            }
        });
        jMenu5.add(JMenuBuscarHorarioPorSalida);

        jBuscarHorarios.setText("Buscar Horarios por Ruta");
        jBuscarHorarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBuscarHorariosActionPerformed(evt);
            }
        });
        jMenu5.add(jBuscarHorarios);

        jMenuItem3.setText("Rutas");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem3);

        jMenuItem4.setText("Pasajes Vendidos");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem4);

        jMenuBar2.add(jMenu5);

        jMenu7.setText("Salir");
        jMenu7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu7MouseClicked(evt);
            }
        });
        jMenu7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu7ActionPerformed(evt);
            }
        });
        jMenuBar2.add(jMenu7);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu7ActionPerformed
        
        System.exit(0);
        
    }//GEN-LAST:event_jMenu7ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed

        escritorio.removeAll();
        escritorio.repaint();
        Horarios gestion = new Horarios();
        gestion.setVisible(true);
        escritorio.add(gestion);
        escritorio.moveToFront(gestion);

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

        escritorio.removeAll();
        escritorio.repaint();
        Pasajeros gestion = new Pasajeros();
        gestion.setVisible(true);
        escritorio.add(gestion);
        escritorio.moveToFront(gestion);

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
                
        escritorio.removeAll();
        escritorio.repaint();
        Rutas gestion = new Rutas();
        gestion.setVisible(true);
        escritorio.add(gestion);
        escritorio.moveToFront(gestion);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenu7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu7MouseClicked
        
        System.exit(0);
        
    }//GEN-LAST:event_jMenu7MouseClicked

    private void jBuscarHorariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBuscarHorariosActionPerformed
        // TODO add your handling code here:
         escritorio.removeAll();
        escritorio.repaint();
        BuscarHorariosPorRuta gestion = new BuscarHorariosPorRuta();
        gestion.setVisible(true);
        escritorio.add(gestion);
        escritorio.moveToFront(gestion);
        
    }//GEN-LAST:event_jBuscarHorariosActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        
        escritorio.removeAll();
        escritorio.repaint();
        PasajesVendidos gestion = new PasajesVendidos();
        gestion.setVisible(true);
        escritorio.add(gestion);
        escritorio.moveToFront(gestion);
        
        
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jPasajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasajeActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        Ventas gestion = new Ventas();
        gestion.setVisible(true);
        escritorio.add(gestion);
        escritorio.moveToFront(gestion);
        
    }//GEN-LAST:event_jPasajeActionPerformed

    private void JMenuBuscarHorarioPorSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuBuscarHorarioPorSalidaActionPerformed
        
        escritorio.removeAll();
        escritorio.repaint();
        BuscarHorariosPorSalida gestion = new BuscarHorariosPorSalida();
        gestion.setVisible(true);
        escritorio.add(gestion);
        escritorio.moveToFront(gestion);
        
    }//GEN-LAST:event_JMenuBuscarHorarioPorSalidaActionPerformed

    private void jMenu5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuEscritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuEscritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuEscritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuEscritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuEscritorio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem JMenuBuscarHorarioPorSalida;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuItem jBuscarHorarios;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jPasaje;
    private javax.swing.JMenu jVenta;
    // End of variables declaration//GEN-END:variables
}
