
package Vistas;

import accesoADatos.PasajeData;
import accesoADatos.RutaData;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import Entidades.*;
import accesoADatos.HorarioData;
import accesoADatos.PasajeroData;
import java.util.ArrayList;

/**
 *
 * @author Deb APBT
 */
public class PasajesVendidos extends javax.swing.JInternalFrame {

    private List<Ruta> rutaR;
    private List<Pasaje> pasajeP;
    private List<Horario> horarioH;
    private List<Pasajero> pasajeroP;
    
    
    private RutaData rutaData;
    private PasajeData pasajData;
    private HorarioData horarioD;
    private PasajeroData pasajeroDT;
    
    private DefaultTableModel modelo;
    
    
    /**
     * Creates new form PasajesVendidos
     */
    public PasajesVendidos() {
        initComponents();
        
        rutaData = new RutaData();
        pasajData = new PasajeData();
        rutaR = rutaData.listarRuta();
        
        horarioD = new HorarioData();
        horarioH = horarioD.obtenerTodosLosHorarios();
        
        pasajeroDT = new PasajeroData();
        pasajeroP = pasajeroDT.listarPasajero();
        
        modelo = new DefaultTableModel();
        
        armarCabecera();
        cargarRutas();
        cargarHorarios();
        cargarPasajeros();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablaPV = new javax.swing.JTable();
        jcbFiltrarPorRuta = new javax.swing.JComboBox();
        JCBFiltrarPorHorario = new javax.swing.JComboBox();
        JCBFiltrarPorPasajero = new javax.swing.JComboBox();
        jbAnularVenta = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pasajes Vendidos");
        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jButton1.setText("Salir");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 2, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Pasajes Vendidos");
        jLabel10.setToolTipText("");
        jLabel10.setAlignmentY(0.0F);
        jLabel10.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(), null));
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Filtrar por Ruta");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Filtrar Por Horario");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Filtrar Por Pasajero");
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jTablaPV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTablaPV);

        jcbFiltrarPorRuta.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jcbFiltrarPorRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbFiltrarPorRutaActionPerformed(evt);
            }
        });

        JCBFiltrarPorHorario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JCBFiltrarPorHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCBFiltrarPorHorarioActionPerformed(evt);
            }
        });

        JCBFiltrarPorPasajero.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JCBFiltrarPorPasajero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCBFiltrarPorPasajeroActionPerformed(evt);
            }
        });

        jbAnularVenta.setBackground(new java.awt.Color(255, 0, 51));
        jbAnularVenta.setText("Anular Venta de Pasaje Emitido");
        jbAnularVenta.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbAnularVenta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbAnularVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAnularVentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
                .addGap(111, 111, 111)
                .addComponent(jButton1)
                .addGap(62, 62, 62))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(145, 145, 145)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JCBFiltrarPorHorario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JCBFiltrarPorPasajero, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcbFiltrarPorRuta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addComponent(jbAnularVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jcbFiltrarPorRuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JCBFiltrarPorHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(JCBFiltrarPorPasajero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jbAnularVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    ////////////////////////////////////////////////////////
    
    //BOTON SALIR
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    // BORRA FILAS TABLA
    private void borrarFilasTabla() {

        int indice = modelo.getRowCount() - 1;
        for (int i = indice; i >= 0; i--) {

            modelo.removeRow(i);
        }
    }
    
    //ARMA CABECERA DE TABLA
    private void armarCabecera() {

        ArrayList<Object> filaCabecera = new ArrayList<>();
        filaCabecera.add("Id Pasaje");
        filaCabecera.add("Ruta");
        filaCabecera.add("Fecha de Viaje");
        filaCabecera.add("Hora de Viaje");
        filaCabecera.add("Asiento");
        filaCabecera.add("Colectivo");
        filaCabecera.add("Pasajero");
        filaCabecera.add("Precio");

        for (Object it : filaCabecera) {

            modelo.addColumn(it);
        }
        
        jTablaPV.setModel(modelo);
    }
    
    ////////////////////////////////////////////////////////
    
    
    
    // CARGAR RUTAS EN COMBO BOX
    private void cargarRutas() {

        for (Ruta item : rutaR) {

            jcbFiltrarPorRuta.addItem(item);
        }
    }
    
    private void cargaDatosPorRuta() {
        
        try {
            
            Ruta select = (Ruta) jcbFiltrarPorRuta.getSelectedItem();
            List<Pasaje> lista = pasajData.obtenerPasajeVendidoPorRuta(select.getIdRuta());

            for (Pasaje a : lista) {

                modelo.addRow(new Object[]{a.getIdPasaje(), a.getRuta(), a.getFechaViaje(), a.getHoraViaje(), a.getAsiento(), a.getColectivo(), a.getPasajero(), a.getPrecio()});

            }
            
            
        } catch (Exception e) {
            
            e.printStackTrace();
        }
        
       
        
    }
    
    
    private void jcbFiltrarPorRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbFiltrarPorRutaActionPerformed
        
        borrarFilasTabla();
        cargaDatosPorRuta();
        
    }//GEN-LAST:event_jcbFiltrarPorRutaActionPerformed

    
    // CARGAR HORARIOS EN COMBO BOX
    private void cargarHorarios() {

        for (Horario item : horarioH) {

            JCBFiltrarPorHorario.addItem(item);
        }
    }
    
    private void cargaDatosPorHorario() {

        Horario select = (Horario) JCBFiltrarPorHorario.getSelectedItem();
        List<Pasaje> lista = pasajData.obtenerPasajeVendidoPorHorario(select.getHoraSalida());

        for (Pasaje b : lista) {

            modelo.addRow(new Object[]{b.getIdPasaje(), b.getRuta(), b.getFechaViaje(), b.getHoraViaje(), b.getAsiento(), b.getColectivo(), b.getPasajero(), b.getPrecio()});
        }
        modelo.fireTableDataChanged();
    }
    
    
    private void JCBFiltrarPorHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBFiltrarPorHorarioActionPerformed
        
        borrarFilasTabla();
        cargaDatosPorHorario();
        
    }//GEN-LAST:event_JCBFiltrarPorHorarioActionPerformed

    
    
    // CARGAR PASAJEROS EN COMBO BOX
    private void cargarPasajeros() {

        for (Pasajero item : pasajeroP) {

            JCBFiltrarPorPasajero.addItem(item);
        }
    }
    

    private void cargaDatosPorPasajero() {

        Pasajero select = (Pasajero) JCBFiltrarPorPasajero.getSelectedItem();
        List<Pasaje> lista = pasajData.obtenerPasajeVendidoPorPasajero(select.getIdPasajero());

        for (Pasaje c : lista) {

            modelo.addRow(new Object[]{c.getIdPasaje(), c.getRuta(), c.getFechaViaje(), c.getHoraViaje(), c.getAsiento(), c.getColectivo(), c.getPasajero(), c.getPrecio()});
        }
        
        modelo.fireTableDataChanged();
    }
    
    
    private void JCBFiltrarPorPasajeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBFiltrarPorPasajeroActionPerformed
       
        borrarFilasTabla();
        cargaDatosPorPasajero();
        
    }//GEN-LAST:event_JCBFiltrarPorPasajeroActionPerformed

    private void jbAnularVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAnularVentaActionPerformed
        // TODO add your handling code here:
        int filaSeleccionada = jTablaPV.getSelectedRow();
        
        if(filaSeleccionada != -1){
            int idPasaje = (Integer)modelo.getValueAt(filaSeleccionada, 0);
            pasajData.borrarPasaje1(idPasaje);
            borrarFilasTabla();       
        }
    }//GEN-LAST:event_jbAnularVentaActionPerformed


    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox JCBFiltrarPorHorario;
    private javax.swing.JComboBox JCBFiltrarPorPasajero;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablaPV;
    private javax.swing.JButton jbAnularVenta;
    private javax.swing.JComboBox jcbFiltrarPorRuta;
    // End of variables declaration//GEN-END:variables
}
